#!/bin/bash
# start.sh
# Copyright (C) 2020 wanghch <wanghch@wanghch-pc>
#
# Distributed under terms of the MIT license.
#
bin=`dirname "$0"`
export AC_HOME=`cd "$bin/"; pwd`
export CUR_DIR=$PWD
. $AC_HOME/bin/conf.sh

run_action $@
